repurposed blog script to suit my flow

diff --git a/scripts/blog b/scripts/blog
--- a/scripts/blog
+++ b/scripts/blog
@@ -1,130 +1,118 @@
 #!/bin/bash
 
 # A bash script that helps me create notes for my blog
-# by running 'blog zet' or 'blog article' a markdown file is created in the proper directory, with my chosen filename.
+# Extensions:
+# - post    creates a new blog post
+# - convert creates a new blog post from an existing note
+# - test    runs 'hugo server' against the blog repo
 
-HOSTING_REPO="$REPOS/github.com/mischavandenburg/tech-blog-hosting/"
+POSTSDIR="$BLOG/content/posts"
+
+# generate_frontmatter generates YAML front matter for a file
+generate_frontmatter() {
+  local file="$1"
+  local date=$(date +"%Y-%m-%d")
+
+  # Format the title by removing dashes
+  local title="${file##*/}"                   # Extract filename
+  title="$(echo $title | sed 's/\.[^.]*$//')" # Remove file extension
+  title="${title//-/ }"                       # Replace dashes with spaces
+
+  cat <<EOF >"$file"
+---
+title: $title
+date: $date
+tags:
+- 
+---
+EOF
+
+  echo -e "\n" >>"$file"
+}
 
 # get_filename prompts the user for a filename
 get_filename() {
-	read -p "Enter a filename: " filename
+  read -p "Enter a filename: " filename
 }
 
-# open_file creates and opens a file in the specified directory
 open_file() {
+  file="$POSTSDIR/$1.md"
 
-	date=$(date +"%Y-%m-%d")
-	timestamp="$(date +"%Y%m%d%H%m")"
-	# Cd into the directory
-	cd "$1" || exit
-	# Create the file in the specified directory
-	touch "$1/$filename.md"
+  touch "$file"
 
-	# cd into second brain
-	cd "$ZETTELKASTEN" || exit
-
-	# Format the title by removing dashes
-	title=$filename
-	title="${title//-/ }"
-
-	# set up the yaml frontmatter
-	echo "---" >>"$1/$filename.md"
-	echo "title: $filename" >>"$1/$filename.md"
-	echo "date: $date" >>"$1/$filename.md"
-
-	if [[ $2 = "zet" ]]; then
-		echo "tags:" >>"$1/$filename.md"
-		echo "- " >>"$1/$filename.md"
-	fi
-
-	if [[ $2 = "article" ]]; then
-		echo "tags:" >>"$1/$filename.md"
-		echo "- Article" >>"$1/$filename.md"
-	fi
-
-	echo "---" >>"$1/$filename.md"
-	echo -en "\n" >>"$1/$filename.md"
-	echo -en "\n" >>"$1/$filename.md"
-	echo -en "\n" >>"$1/$filename.md"
-	echo "## Links:" >>"$1/$filename.md"
-	echo -en "\n" >>"$1/$filename.md"
-	echo "$timestamp" >>"$1/$filename.md"
-
-	# Open the file in Neovim
-	nvim '+ normal 2GzzA' "$1/$filename.md" -c :NoNeckPain
-
+  generate_frontmatter $file
+  # Open the file in Neovim
+  nvim '+ normal 2GzzA' "$file" -c :NoNeckPain
 }
 
 # Check the value of the first parameter
 case "$1" in
-zet)
-	# Call the function to get the filename
-	get_filename
+post)
+  echo "Got parameter: $2"
 
-	# Call the function to create and open the file in the specified directory
-	open_file "$HOME/websites/blog/content/zet" "zet"
+  if [[ -z "$2" ]]; then
+    get_filename
+  else
+    filename="$2"
+  fi
+  echo "Got file name: $filename"
+  open_file "$filename"
+  ;;
 
-	;;
-article)
-	# Call the function to get the filename
-	get_filename
+convert)
+  if [[ -z "$2" ]]; then
+    get_filename
+  else
+    filename="$2"
+  fi
 
-	# Call the function to create and open the file in the specified directory
-	open_file "$HOME/websites/blog/content/zet/articles" "article"
-	;;
+  echo "Got file: $filename"
 
-reset)
-	rm -rf "$HOME/websites/blog/public"
-	cd "$HOME/websites/blog/" || exit
-	hugo
-	hugo server --disableFastRender
-	;;
+  note_path="$filename"
 
-pub)
-	# ask for commit message, rebuild the site, push to blog repo, then push to hosting repo
-	read -p "Enter commit message: " commitmessage
+  if [[ ! -f "$note_path" ]]; then
+    echo "File does not exist: $note_path"
+    exit 1
+  fi
 
-	read -p "Would you like to tweet + toot that? (y/n) " will_tweet
+  touch "$note_path"
 
-	if [[ $will_tweet == [Yy]* ]]; then
-		read -p "Enter tags, or press enter to post without tags: " tags
-	fi
+  note_name=$(basename "$note_path" | sed 's/\.[^.]*$//')
 
-	cd "$HOME/websites/blog/" || exit
-	rm -rf "$HOME/websites/blog/public"
-	hugo
-	git add .
-	git commit -m "$commitmessage"
-	git push
-	rm -rf "$HOSTING_REPO*"
-	cp -r "$HOME"/websites/blog/public/* "$HOSTING_REPO"
-	cd "$HOSTING_REPO" || exit
-	git add .
-	git commit -m "$commitmessage"
-	git push
+  echo "Got note name: $note_name"
 
-	if [[ $will_tweet == [Yy]* ]]; then
-		echo "Waiting 10 seconds to allow it to publish before tweeting."
-		sleep 10
+  post_path="$POSTSDIR/$note_name.md"
 
-		# post to twitter/mastodon without tags
-		if [[ $tags == "" ]]; then
-			tweet
-			toot
-			exit
-		fi
-		tweet "$tags"
-		toot "$tags"
-	fi
-	;;
+  echo "Got post path: $post_path"
+
+  if [[ -e "$post_path" ]]; then
+    echo "Post already exists: $post_path"
+    exit 1
+  fi
+
+  generate_frontmatter "$post_path"
+
+  cat "$filename" >>"$post_path"
+
+  sed -i '/^\[\[/d' "$post_path"
+
+  echo -e "Converted note to blog post:\n$filename -> $note_path"
+
+  nvim '+ normal 2GzzA' "$post_path" -c :NoNeckPain
+  ;;
+
+test)
+  cd "$BLOG" || exit
+  hugo server
+  ;;
 
 "")
-	# Change to the websites/blog directory if no argument was given
-	cd "$HOME/websites/blog" || exit
-	;;
+  # Change to the blog directory if no argument was given
+  cd "$BLOG" || exit
+  ;;
 
 *)
-	# Print an error message if the parameter was not "zet" or "article"
-	echo "Error: Invalid parameter. Usage: blog zet|article|pub"
-	;;
+  # Print an error message if the parameter was not "post", "convert" or "test"
+  echo "Error: Invalid parameter. Usage: blog post|convert|test"
+  ;;
 esac
